= Exercices
== Serialisation
Dans cet exercice, la persistance sera assurée par la sérialisation Java.

. Rendez les classes de l’application sérialisables et vérifiez en le fonctionnement avec des tests unitaires.
. Définissez l’interface DAO pour les opérations CRUD ainsi qu’une fabrique pour l’instanciation des DAO.
. Implémentez cette interface avec la sérialisation Java.

== JDBC
Dans cet exercice, la persistance sera assurée par l’API JDBC.
Vous reprendrez le travail de l’exercice #exo:serialisation[[exo:serialisation]] et vous le compléterez.
Vous pouvez utilisez le SGBD http://db.apache.org/derby/[derby] en mode embarqué.

. Proposez une nouvelle implémentation des DAO en utilisant JDBC.
. Mettez en œuvre une fabrique abstraite pour la création des DAO.

== JPA
Dans cet exercice, la persistance sera assurée par l’API JPA.
Vous reprendrez le travail de l’exercice #exo:jdbc[[exo:jdbc]] et vous le compléterez.
En plus de http://db.apache.org/derby/[derby], vous utiliserez le _provider JPA_ http://hibernate.org/orm/[Hibernate ORM].

. Proposez une nouvelle implémentation des DAO en utilisant JPA/Hibernate.
. Intégrez cette implémentation dans la fabrique abstraite.
